"""Add image quality fields to document_anchors

Revision ID: 0f04a8ef4f1b
Revises: 
Create Date: 2026-03-25 00:59:51.152508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f04a8ef4f1b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_anchors', sa.Column('image_quality_score', sa.Float(), nullable=True))
    op.add_column('document_anchors', sa.Column('image_quality_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(None, 'signing_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'signing_logs', 'users', ['signer_public_key_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'signing_logs', type_='foreignkey')
    op.drop_constraint(None, 'signing_logs', type_='foreignkey')
    op.drop_column('document_anchors', 'image_quality_details')
    op.drop_column('document_anchors', 'image_quality_score')
    # ### end Alembic commands ###
